
OBJS = makempq.o 
INCLUDE = -I../../include
CFLAGS = -g3 -funsigned-char -O0 $(INCLUDE) -DMPQLIB
#LDFLAGS = -lstdc++ -lStorm -lz
LDFLAGS = -lstdc++ -lmpq -lz

makempq: makempq.o
	gcc $(LDFLAGS) $(OBJS) -o makempq

makempq.o: makempq.cpp
	gcc -c $(CFLAGS) makempq.cpp -o makempq.o
clean:
	-rm makempq makempq.o
	
