//====================objects defines from units
#define LARVAEREFRESHTIME	300
//=====================================================
#define SC_MARINEOBJ			0
#define SC_GHOSTOBJ			1
#define SC_VULTUREOBJ			2
#define SC_GOLIATHOBJ			3
#define SC_GOLIATHTURRETOBJ		4
#define SC_TANKNORMALOBJ		5
#define SC_TANKNORMALTURRETOBJ		6
#define SC_SCVOBJ			7
#define SC_WRAITHOBJ			8
#define SC_SCIENCEVESSELOBJ		9
#define SC_HERO_GUIMONTAGOBJ		10		//HERO
#define SC_DROPSHIPOBJ			11
#define SC_BATTLECRUISEROBJ		12
#define SC_VULTUREMINEOBJ		13
#define SC_NUKEOBJ			14
#define SC_CIVILIANOBJ			15
#define SC_HERO_SARAKERRIGANOBJ		16		//HERO
#define SC_HERO_ALANSCHEZAROBJ		17		//HERO
#define SC_HERO_ALANSCHEZARTURRETOBJ	18		//HERO
#define SC_HERO_JIMRAYNORVOBJ		19		//HERO
#define SC_HERO_JIMRAYNORMOBJ		20		//HERO
#define SC_HERO_TOMKAZANSKYOBJ		21		//HERO
#define SC_HERO_MAGELLANOBJ		22		//HERO
#define SC_HERO_EDMUNDDUKETMOBJ		23		//HERO
#define SC_HERO_EDMUNDDUKETMTURRETOBJ	24		//HERO
#define SC_HERO_EDMUNDDUKESMOBJ		25		//HERO
#define SC_HERO_EDMUNDDUKESMTURRETOBJ	26		//HERO
#define SC_HERO_ARCTURUSMENGSKOBJ 	27		//HERO
#define SC_HERO_HYPERIONOBJ 		28		//HERO
#define SC_HERO_NORAD2OBJ 		29		//HERO
#define SC_TANKSIEGEOBJ			30
#define SC_TANKSIEGETURRETOBJ		31
#define SC_FIREBATOBJ			32
#define SC_SCANNERSWEEP			33
#define SC_MEDICOBJ			34
#define SC_LARVAEOBJ			35
#define SC_EGGOBJ			36
#define SC_ZERGLINGOBJ			37
#define SC_HYDRALISKOBJ			38
#define SC_ULTRALISKOBJ			39
#define SC_BROODLINGOBJ			40
#define SC_DRONEOBJ			41
#define SC_OVERLORDOBJ			42
#define SC_MUTALISKOBJ			43
#define SC_GUARDIANOBJ			44
#define SC_QUEENOBJ			45
#define SC_DEFILEROBJ			46
#define SC_SCOURGEOBJ			47
#define SC_HERO_TORASQUEOBJ 		48		//HERO
#define SC_HERO_MATRIARCHOBJ 		49		//HERO
#define SC_BUGGUYOBJ			50
#define SC_HERO_INFESTEDSARAKERRIGANOBJ	51		//HERO
#define SC_HERO_UNCLEANONEOBJ 		52		//HERO
#define SC_HERO_HUNTERKILLEROBJ		53		//HERO
#define SC_HERO_DEVOURINGONEOBJ		54		//HERO
#define SC_HERO_KUKULZAMOBJ 		55		//HERO
#define SC_HERO_KUKULZAGOBJ 		56		//HERO
#define SC_HERO_YGGDRASILLOBJ 		57		//HERO
#define SC_VALKYRIEOBJ			58
#define SC_MUTALISKCOCOONOBJ		59
#define SC_CORSAIROBJ			60
#define SC_DARKTEMPLAROBJ		61
#define SC_DEVOUREROBJ			62
#define SC_DARKARCHONOBJ		63
#define SC_PROBEOBJ			64
#define SC_ZEALOTOBJ			65
#define SC_DRAGOONOBJ			66
#define SC_HIGHTEMPLAROBJ		67
#define SC_ARCHONOBJ			68
#define SC_SHUTTLEOBJ			69
#define SC_SCOUTOBJ			70
#define SC_ARBITEROBJ			71
#define SC_CARRIEROBJ			72
#define SC_INTERCEPTOROBJ		73
#define SC_HERO_DARKTEMPLAROBJ		74		//HERO
#define SC_HERO_ZERATULOBJ		75		//HERO
#define SC_HERO_ARCHONOBJ		76		//HERO
#define SC_HERO_FENIXZOBJ		77		//HERO
#define SC_HERO_FENIXDOBJ		78		//HERO
#define SC_HERO_TASSADAROBJ		79		//HERO
#define SC_HERO_MOJOOBJ			80		//HERO
#define SC_HERO_WARBRINGEROBJ		81		//HERO
#define SC_HERO_GANTRITHOROBJ		82		//HERO
#define SC_REAVEROBJ			83
#define SC_OBSERVEROBJ			84
#define SC_SCARABOBJ			85
#define SC_HERO_DANIMOTHOBJ		86		//HERO
#define SC_HERO_ALDARISOBJ		87		//HERO
#define SC_HERO_ARTANISOBJ		88		//HERO
                                	
#define SC_NEUTRAL_CRITTER1		89		//rhynadon (badlands)
#define SC_NEUTRAL_CRITTER2		90		//bengalaas(jungle)
#define SC_NEUTRAL_CRITTER3		93		//scandid(desert)
#define SC_NEUTRAL_CRITTER4		94		//kakaru(twilight)
#define SC_NEUTRAL_CRITTER5		95		//ragnasaur(ashworld)
#define SC_NEUTRAL_CRITTER6		96		//ursadon(iceworld)
                                	
#define SC_LURKEREGGOBJ			97
#define SC_HERO_RASZAGALOBJ		98		//HERO
#define SC_HERO_SAMIRDURANOBJ		99		//HERO
#define SC_HERO_ALEXEISTUKOVOBJ		100		//HERO
#define SC_MAPREVEALEROBJ		101		//????
#define SC_HERO_GERARDDUGALLEOBJ	102		//HERO
                                	
#define SC_LURKEROBJ			103
#define SC_HERO_INFESTEDSAMIRDURANOBJ 	104		//HERO
#define SC_MISC_DISRUPTIONWEB		105
                                	
#define SC_COMMCENTEROBJ		106
#define SC_COMSATSTATIONOBJ		107
#define SC_NUCLEARSILOOBJ		108
#define SC_SUPPLYDEPOTOBJ		109
#define SC_REFINERYOBJ			110
#define SC_BARRACKSOBJ			111
#define SC_ACCADEMYOBJ			112
#define SC_FACTORYOBJ			113
#define SC_STARPORTOBJ			114
#define SC_CONTROLTOWEROBJ		115
#define SC_SCIENCEFACILITYOBJ		116
#define SC_COVERTOPSOBJ			117
#define SC_PHYSICSLABOBJ		118
#define SC_MACHINESHOPOBJ		120
#define SC_ENGINEERINGBAYOBJ		122
#define SC_ARMORYOBJ			123
#define SC_MISSILETURRETOBJ		124
#define SC_BUNKEROBJ			125
#define SC_NORAD2CRASHEDOBJ		126
#define SC_IONCANNONOBJ			127
#define SC_INFCOMMCENTEROBJ		130
#define SC_HATCHERYOBJ			131
#define SC_LAIROBJ			132
#define SC_HIVEOBJ			133
#define SC_NYDUSCANALOBJ		134
#define SC_HYDRALISKDENOBJ		135
#define SC_DEFILERMOUNDOBJ		136
#define SC_GREATERSPIREOBJ		137
#define SC_QUEENNESTOBJ			138
#define SC_EVOLUTIONCHAMBEROBJ		139
#define SC_ULTRALISKCAVERNOBJ		140
#define SC_SPIREOBJ			141
#define SC_SPAWNINGPOOLOBJ		142
#define SC_CREEPCOLONYOBJ		143
#define SC_SPORECOLONYOBJ		144
#define SC_SUNKENCOLONYOBJ		146
#define SC_EXTRACTOROBJ			149
#define SC_MATURECRISALISOBJ		150
#define SC_CEREBRATEOBJ			151
#define SC_HERO_CEREBRATEDAGGOTH	152
#define SC_NEXUSOBJ			154
#define SC_ROBOTICSFACILITYOBJ		155
#define SC_PYLONOBJ			156
#define SC_ASSIMILATOROBJ		157
#define SC_OBSERVATORYOBJ		159
#define SC_GATEWAYOBJ			160
#define SC_PHOTONCANONOBJ		162
#define SC_CITADELOFADUNOBJ		163
#define SC_CYBERNETICCOREOBJ		164
#define SC_TEMPLARARCHIVESOBJ		165
#define SC_FORGEOBJ			166
#define SC_STARGATEOBJ			167
#define SC_FLEETBEACONOBJ		169
#define SC_ARBITERTRIBUNALOBJ		170
#define SC_ROBOTICSSUPPORTBAYOBJ	171
#define SC_BATTERYOBJ			172
#define SC_MINERAL1OBJ			176
#define SC_MINERAL2OBJ			177
#define SC_MINERAL3OBJ			178
#define SC_PSISTORMOBJ			179
#define SC_NUKEPOINTOBJ			180
#define SC_GEYSEROBJ			188
#define SC_WARPGATE			189
                                	
#define SC_ZERGBEACONOBJ		194
#define SC_TERRANBEACONOBJ		195
#define SC_PROTOSSBEACONOBJ		196
#define SC_ZERGFLAGBEACONOBJ		197
#define SC_TERRANFLAGBEACONOBJ		198
#define SC_PROTOSSFLAGBEACONOBJ		199
                                	
#define SC_MISC_POWERGENERATOR		200
#define SC_OVERMINDCOCOONOBJ		201
#define SC_MISC_DARKSWARM		202
                                	
#define SC_FLOORHATCHOBJ		204
#define SC_LEFTUPPERLEVELDOOROBJ	205
#define SC_RIGHTUPPERLEVELDOOROBJ	206
#define SC_LEFTPITDOOROBJ		207
#define SC_RIGHTPITDOOROBJ		208
                                	
#define SC_STARTLOC			214
#define SC_YOUNGCRISALISOBJ		216
#define SC_PSIEMITTEROBJ		217
#define SC_DATADISKOBJ			218
#define SC_KHADARYNCRYSTALOBJ		219
                                	
#define SC_CARRY_MINERAL1		220
#define SC_CARRY_MINERAL2		221
#define SC_CARRY_PROTOSS_GASORB1	222
#define SC_CARRY_PROTOSS_GASORB2	223
#define SC_CARRY_ZERG_GASORB1		224
#define SC_CARRY_ZERG_GASORB2		225
#define SC_CARRY_TERRAN_GASORB1		226
#define SC_CARRY_TERRAN_GASORB2		227
                                	
#define	SC_UNITNR			228
#define	SC_EVERYUNIT			229
#define	SC_MENUNIT			230
#define	SC_BUILDUNIT			231
#define	SC_FACTORYUNIT			232
#define	SC_MAXUNITIDS			233

#define SC_NOUNITNR			255


#define SC_GEYSERBUILDSOBJ		SC_EXTRACTOROBJ
#define SC_MINERALSOBJ			SC_MINERAL1OBJ

#define WEAPONID_SPIDERMINES 		6
#define WEAPONID_YAMATOGUN 		30
#define WEAPONID_NUCLEARMISSILE 	31
#define WEAPONID_LOCKDOWN		32
#define WEAPONID_IRRADIATE		34
#define WEAPONID_ZERGLING1CLAWS		35
#define WEAPONID_ZERGLING2CLAWS		36

#define WEAPONID_INFESTEDSUICIDE	54
#define WEAPONID_PLAGUE			60
#define WEAPONID_SCARAB			82
#define WEAPONID_PSISTORM		84
#define WEAPONID_CORROSIVEACID		104
#define WEAPONID_FEEDBACK		106
#define WEAPONID_SUBTERRANEANSPINES	109
#define WEAPONID_CARRIERRANGE		WEAPONID_LOCKDOWN
#define WEAPONID_REAVERRANGE		WEAPONID_LOCKDOWN

#define SFXDATA_ERRORTARGET_ZERG		1
#define SFXDATA_ERRORTARGET_TERRAN		2
#define SFXDATA_ERRORTARGET_PROTOSS		3
#define SFXDATA_SOUNDSELECT			15
#define SFXDATA_BURROWDOWN			16
#define SFXDATA_BURROWUP			17
#define SFXDATA_BUILDFIRE1			18
#define SFXDATA_INTONYDUS			19
#define SFXDATA_GASDEPLETED			20
#define SFXDATA_YOUWIN				21
#define SFXDATA_YOULOSE				22
#define SFXDATA_TRANSMISSION			23
#define SFXDATA_ZRESCUE				32
#define SFXDATA_TRESCUE				33
#define SFXDATA_PRESCUE				34

#define SFXDATA_ZINTRANSPORT			40
#define SFXDATA_TINTRANSPORT			41
#define SFXDATA_PINTRANSPORT			42

#define SFXDATA_ZOUTTRANSPORT			43
#define SFXDATA_TOUTTRANSPORT			44
#define SFXDATA_POUTTRANSPORT			45


#define SFXDATA_LAUNCHNUKE			84
#define SFXDATA_ZERGBUILDWARPEND		135
#define SFXDATA_TERRANBUILDWARPEND		136
#define SFXDATA_MOUSEDOWN			165
#define SFXDATA_MOUSEOVER			166

#define SFXDATA_BNETCLICK			167
#define SFXDATA_SCOREFILL			168
#define SFXDATA_SCOREFILLEND			169
#define SFXDATA_COUNTDOWN			170
#define SFXDATA_SNDMENULOCK			171
#define SFXDATA_SNDMENUIN			172
#define SFXDATA_SNDMENUOUT			173
#define SFXDATA_CLOAKIN				273
#define SFXDATA_CLOAKOUT			274
#define SFXDATA_BUILDFIRE2			403
#define SFXDATA_PROTOSSBUILDWARPBEGIN		528
#define SFXDATA_PROTOSSBUILDWARPEND		529
#define SFXDATA_PROTOSSBUILDWARPINPROGRESS	530
#define SFXDATA_HALLUCINATIONDIE		619
#define SFXDATA_ZERGBUILDWARPCANCEL		774
#define SFXDATA_DISRUPTIONWEB			1059

#define FLINGYID_GOLIATHTURRET			76
#define FLINGYID_HALOROCKETS			202

#define IMAGEID_EMPTY				0
#define IMAGEID_TEXTURE				210
#define IMAGEID_WARPANCHOR			211
#define IMAGEID_NUKE_TARGET_DOT			233

#define IMAGEID_BUNKERFIREOVERLAY		306

#define IMAGEID_VESPENEGEYSER			344

#define IMAGEID_STASISFIELDHIT			364

#define IMAGEID_RECHARGESHIELDSMALL		368
#define IMAGEID_RECHARGESHIELDMEDIUM		369
#define IMAGEID_RECHARGESHIELDLARGE		370

#define IMAGEID_DEFENSIVEMATRIXHIT1		377
#define IMAGEID_ENSNARECLOUD			383
#define IMAGEID_PLAGUECLOUD			387

#define IMAGEID_SHIELDOVERLAY			424
#define IMAGEID_GEYSERSMOKE1			430
#define IMAGEID_DEPLETEDGEYSERSMOKE1		435
#define IMAGEID_MOUSEDEST			445
#define IMAGEID_BLOODFLAMESMALL1		450
#define IMAGEID_BLOODFLAMELARGE1		472
#define IMAGEID_HALLUCINATIONHIT		545
#define IMAGEID_HALLUCINATIONDIE1		557
#define IMAGEID_PYLONSELECTAREA1		584
#define IMAGEID_PYLONSELECTAREA4		587

#define IMAGEID_ACIDSPORES1			986
#define IMAGEID_ACIDSPOREM1			990
#define IMAGEID_ACIDSPOREL1			994
#define IMAGEID_MAELSTROMHIT			998

#define STATTXT_UNABLEATTACKTARGET		878
#define STATTXT_UNABLEREPAIRTARGET		882

